export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    registerOwner: "/auth/register/owner",
    registerStaff: "/auth/register/staff",
    requestResetPassword: "/auth/reset-password/request",
    verifyResetPassword: "/auth/reset-password/verify",
    confirmResetPassword: "/auth/reset-password/confirm",
    profile: "/auth/profile",
  },
  shops: {
    list: "/shops",
    create: "/shops",
    update: (shopId: string) => `/shops/${shopId}`,
    categories: (shopId: string) => `/shops/${shopId}/categories`,
    suppliers: (shopId: string) => `/shops/${shopId}/suppliers`,
    products: (shopId: string) => `/shops/${shopId}/products`,
    lowStockProducts: (shopId: string) => `/shops/${shopId}/products/low-stock`,
    product: (shopId: string, productId: string) => `/shops/${shopId}/products/${productId}`,
    sales: (shopId: string) => `/shops/${shopId}/sales`,
    saleDetail: (shopId: string, saleId: string) => `/shops/${shopId}/sales/${saleId}`,
    customers: (shopId: string) => `/shops/${shopId}/customers`,
    customerDetail: (shopId: string, customerId: string) => `/shops/${shopId}/customers/${customerId}`,
    debts: (shopId: string) => `/shops/${shopId}/debts`,
    debtPayments: (shopId: string, debtId: string) => `/shops/${shopId}/debts/${debtId}/payments`,
    dashboard: (shopId: string) => `/shops/${shopId}/dashboard`,
    analytics: (shopId: string) => `/shops/${shopId}/analytics`,
  },

  admin: {
    stats: "/admin/stats",
    shops: "/admin/shops",
    suspendShop: (shopId: string) => `/admin/shops/${shopId}/suspend`,
    activateShop: (shopId: string) => `/admin/shops/${shopId}/activate`,
    users: "/admin/users",
    suspendUser: (userId: string) => `/admin/users/${userId}/suspend`,
    activateUser: (userId: string) => `/admin/users/${userId}/activate`,
  },
} as const;

