export const API_ENDPOINTS = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    registerOwner: "/auth/register/owner",
    registerStaff: "/auth/register/staff",
    requestResetPassword: "/auth/reset-password/request",
    verifyResetPassword: "/auth/reset-password/verify",
    confirmResetPassword: "/auth/reset-password/confirm",
    profile: "/auth/profile",
  },
  shops: {
    list: "/shops",
    create: "/shops",
    update: (shopId: string) => `/shops/${shopId}`,
    categories: (shopId: string) => `/shops/${shopId}/categories`,
    category: (shopId: string, categoryId: string) => `/shops/${shopId}/categories/${categoryId}`,
    suppliers: (shopId: string) => `/shops/${shopId}/suppliers`,
    products: (shopId: string) => `/shops/${shopId}/products`,
    lowStockProducts: (shopId: string) => `/shops/${shopId}/products/low-stock`,
    expiringProducts: (shopId: string) => `/shops/${shopId}/products/expiring`,
    product: (shopId: string, productId: string) => `/shops/${shopId}/products/${productId}`,
    sales: (shopId: string) => `/shops/${shopId}/sales`,
    saleDetail: (shopId: string, saleId: string) => `/shops/${shopId}/sales/${saleId}`,
    saleReturns: (shopId: string, saleId: string) => `/shops/${shopId}/sales/${saleId}/returns`,
    customers: (shopId: string) => `/shops/${shopId}/customers`,
    customerDetail: (shopId: string, customerId: string) => `/shops/${shopId}/customers/${customerId}`,
    debts: (shopId: string) => `/shops/${shopId}/debts`,
    debtPayments: (shopId: string, debtId: string) => `/shops/${shopId}/debts/${debtId}/payments`,
    expenses: (shopId: string) => `/shops/${shopId}/expenses`,
    expense: (shopId: string, expenseId: string) => `/shops/${shopId}/expenses/${expenseId}`,
    staff: (shopId: string) => `/shops/${shopId}/staff`,
    staffMember: (shopId: string, staffId: string) => `/shops/${shopId}/staff/${staffId}`,
    dashboard: (shopId: string) => `/shops/${shopId}/dashboard`,
    analytics: (shopId: string) => `/shops/${shopId}/analytics`,
    notifications: (shopId: string) => `/shops/${shopId}/notifications`,
    notificationsUnreadCount: (shopId: string) => `/shops/${shopId}/notifications/unread-count`,
    markNotificationRead: (shopId: string, id: string) => `/shops/${shopId}/notifications/${id}/read`,
    markAllNotificationsRead: (shopId: string) => `/shops/${shopId}/notifications/read-all`,
  },

  admin: {
    stats: "/admin/stats",
    shops: "/admin/shops",
    owners: "/admin/owners",
    suspendShop: (shopId: string) => `/admin/shops/${shopId}/suspend`,
    activateShop: (shopId: string) => `/admin/shops/${shopId}/activate`,
    users: "/admin/users",
    suspendUser: (userId: string) => `/admin/users/${userId}/suspend`,
    activateUser: (userId: string) => `/admin/users/${userId}/activate`,
    notifications: "/admin/notifications",
    notificationsUnreadCount: "/admin/notifications/unread-count",
    markNotificationRead: (id: string) => `/admin/notifications/${id}/read`,
    markAllNotificationsRead: "/admin/notifications/read-all",
  },
} as const;

